import type { Evento } from "./types";

// Copia de los datos de Supabase + 2 casos extra para diseñar.
// Las imágenes reales aún no existen, por eso se usan de relleno.
export const eventosPrueba: Evento[] = [
    {
        id_evento: "evt-101",
        nombre_evento: "Feria de Innovación TITEC",
        descripcion_evento: "Muestra anual de proyectos de ingeniería y tecnología.",
        lugar_evento: "Auditorio Principal UV",
        fecha_evento: "2026-10-15T10:00:00+00:00",
        hora_evento: "10:00",
        imagen_evento: "https://picsum.photos/seed/evt101/600/300",
        precio_final_evento: 0,
        tipo_evento: "gratuito",
        categoria_evento: "academico",
        estado_evento: "disponible",
        stock_actual: 150,
        promedio_calificacion: 4.8,
        total_resenas: 12,
        es_pasado: false,
    },
    {
        id_evento: "evt-102",
        nombre_evento: "Fiesta de Generación Informática",
        descripcion_evento: "Fiesta de fin de semestre para estudiantes y egresados.",
        lugar_evento: "Centro de Eventos El Huevo",
        fecha_evento: "2026-11-05T22:00:00+00:00",
        hora_evento: "22:00",
        imagen_evento: "https://picsum.photos/seed/evt102/600/300",
        precio_final_evento: 5000,
        tipo_evento: "pagado",
        categoria_evento: "fiesta",
        estado_evento: "disponible",
        stock_actual: 300,
        promedio_calificacion: 4.2,
        total_resenas: 5,
        es_pasado: false,
    },
    {
        id_evento: "evt-103",
        nombre_evento: "Torneo Interescuelas Valorant",
        descripcion_evento: "Campeonato oficial universitario de deportes electrónicos.",
        lugar_evento: "Laboratorios de Computación UV",
        fecha_evento: "2026-10-20T15:00:00+00:00",
        hora_evento: "15:00",
        imagen_evento: "https://picsum.photos/seed/evt103/600/300",
        precio_final_evento: 2000,
        tipo_evento: "pagado",
        categoria_evento: "deporte",
        estado_evento: "agotado",
        stock_actual: 0,
        promedio_calificacion: 5.0,
        total_resenas: 45,
        es_pasado: false,
    },
    {
        id_evento: "evt-104",
        nombre_evento: "Charla: IA y Ética",
        descripcion_evento: "Conversatorio con académicos invitados sobre IA responsable.",
        lugar_evento: "Sala 204, Edificio de Ingeniería",
        fecha_evento: "2026-10-30T17:30:00+00:00",
        hora_evento: "17:30",
        imagen_evento: "https://picsum.photos/seed/evt104/600/300",
        precio_final_evento: 0,
        tipo_evento: "gratuito",
        categoria_evento: null,
        estado_evento: "disponible",
        stock_actual: 8,
        promedio_calificacion: 0,
        total_resenas: 0,
        es_pasado: false,
    },
    {
        id_evento: "evt-105",
        nombre_evento: "Congreso de Ciencias Sociales",
        descripcion_evento: "Ponencias y mesas de trabajo sobre investigación social.",
        lugar_evento: "Aula Magna UV",
        fecha_evento: "2026-09-10T09:00:00+00:00",
        hora_evento: "09:00",
        imagen_evento: "https://picsum.photos/seed/evt105/600/300",
        precio_final_evento: 3000,
        tipo_evento: "pagado",
        categoria_evento: "academico",
        estado_evento: "pasado",
        stock_actual: 40,
        promedio_calificacion: 3.9,
        total_resenas: 18,
        es_pasado: true,
    },
    {
        id_evento: "evt-109",
        nombre_evento: "Charla de Innovación",
        descripcion_evento: "Innovación en startups.",
        lugar_evento: "Auditorio C",
        fecha_evento: "2026-11-20T10:00:00+00:00",
        hora_evento: "10:00",
        imagen_evento: "https://picsum.photos/seed/evt109/800/400",
        precio_final_evento: 2000,
        tipo_evento: "pagado",
        categoria_evento: "charla",
        estado_evento: "cancelado",
        stock_actual: 60,
        promedio_calificacion: 0,
        total_resenas: 0,
        es_pasado: false,
    },
];