import type { Evento } from "./types";

// Copia de los datos de Supabase + 2 casos extra para diseñar.
// Las imágenes reales aún no existen, por eso se usan de relleno.
export const eventosPrueba: Evento[] = [
    {
        evento_id: "evt-101",
        evento_titulo: "Feria de Innovación TITEC",
        evento_descripcion: "Muestra anual de proyectos de ingeniería y tecnología.",
        evento_lugar: "Auditorio Principal UV",
        evento_fecha: "2026-10-15T10:00:00+00:00",
        evento_hora: "10:00",
        evento_imagen: "https://picsum.photos/seed/evt101/600/300",
        evento_precio_final: 0,
        evento_tipo: "gratuito",
        evento_categoria: "academico",
        evento_estado: "disponible",
        inventario_stock: 150,
        resena_calificacion_promedio: 4.8,
        resena_total: 12,
    },
    {
        evento_id: "evt-102",
        evento_titulo: "Fiesta de Generación Informática",
        evento_descripcion: "Fiesta de fin de semestre para estudiantes y egresados.",
        evento_lugar: "Centro de Eventos El Huevo",
        evento_fecha: "2026-11-05T22:00:00+00:00",
        evento_hora: "22:00",
        evento_imagen: "https://picsum.photos/seed/evt102/600/300",
        evento_precio_final: 5000,
        evento_tipo: "pagado",
        evento_categoria: "fiesta",
        evento_estado: "disponible",
        inventario_stock: 300,
        resena_calificacion_promedio: 4.2,
        resena_total: 5,
    },
    {
        evento_id: "evt-103",
        evento_titulo: "Torneo Interescuelas Valorant",
        evento_descripcion: "Campeonato oficial universitario de deportes electrónicos.",
        evento_lugar: "Laboratorios de Computación UV",
        evento_fecha: "2026-10-20T15:00:00+00:00",
        evento_hora: "15:00",
        evento_imagen: "https://picsum.photos/seed/evt103/600/300",
        evento_precio_final: 2000,
        evento_tipo: "pagado",
        evento_categoria: "deporte",
        evento_estado: "agotado",
        inventario_stock: 0,
        resena_calificacion_promedio: 5.0,
        resena_total: 45,
    },
    {
        evento_id: "evt-104",
        evento_titulo: "Charla: IA y Ética",
        evento_descripcion: "Conversatorio con académicos invitados sobre IA responsable.",
        evento_lugar: "Sala 204, Edificio de Ingeniería",
        evento_fecha: "2026-10-30T17:30:00+00:00",
        evento_hora: "17:30",
        evento_imagen: "https://picsum.photos/seed/evt104/600/300",
        evento_precio_final: 0,
        evento_tipo: "gratuito",
        evento_categoria: null,
        evento_estado: "disponible",
        inventario_stock: 8,
        resena_calificacion_promedio: 0,
        resena_total: 0,
    },
    {
        evento_id: "evt-105",
        evento_titulo: "Congreso de Ciencias Sociales",
        evento_descripcion: "Ponencias y mesas de trabajo sobre investigación social.",
        evento_lugar: "Aula Magna UV",
        evento_fecha: "2026-09-10T09:00:00+00:00",
        evento_hora: "09:00",
        evento_imagen: "https://picsum.photos/seed/evt105/600/300",
        evento_precio_final: 3000,
        evento_tipo: "pagado",
        evento_categoria: "academico",
        evento_estado: "pasado",
        inventario_stock: 40,
        resena_calificacion_promedio: 3.9,
        resena_total: 18,
    },
    {
        evento_id: "evt-109",
        evento_titulo: "Charla de Innovación",
        evento_descripcion: "Innovación en startups.",
        evento_lugar: "Auditorio C",
        evento_fecha: "2026-11-20T10:00:00+00:00",
        evento_hora: "10:00",
        evento_imagen: "https://picsum.photos/seed/evt109/800/400",
        evento_precio_final: 2000,
        evento_tipo: "pagado",
        evento_categoria: "charla",
        evento_estado: "cancelado",
        inventario_stock: 60,
        resena_calificacion_promedio: 0,
        resena_total: 0,
    },
];